export const SKILLS = {
  Frontend: [
    { name: "React", level: 95, icon: "⚛️" },
    { name: "Next.js", level: 88, icon: "▲" },
    { name: "TypeScript", level: 85, icon: "🔷" },
    { name: "Tailwind CSS", level: 92, icon: "🎨" },
    { name: "Framer Motion", level: 80, icon: "🎬" },
    { name: "Vue.js", level: 72, icon: "💚" },
  ],
  Backend: [
    { name: "Node.js", level: 90, icon: "🟢" },
    { name: "Express.js", level: 92, icon: "🚀" },
    { name: "Python", level: 78, icon: "🐍" },
    { name: "REST APIs", level: 95, icon: "🔗" },
    { name: "GraphQL", level: 70, icon: "◆" },
    { name: "Socket.io", level: 75, icon: "⚡" },
  ],
  Database: [
    { name: "MongoDB", level: 88, icon: "🍃" },
    { name: "PostgreSQL", level: 82, icon: "🐘" },
    { name: "Redis", level: 70, icon: "🔴" },
    { name: "MySQL", level: 80, icon: "🐬" },
    { name: "Prisma", level: 75, icon: "💎" },
    { name: "Mongoose", level: 90, icon: "📦" },
  ],
  Tools: [
    { name: "Git & GitHub", level: 95, icon: "🐙" },
    { name: "Docker", level: 78, icon: "🐳" },
    { name: "AWS", level: 70, icon: "☁️" },
    { name: "Vercel", level: 90, icon: "▲" },
    { name: "Figma", level: 75, icon: "🎭" },
    { name: "VS Code", level: 98, icon: "💻" },
  ],
};

export const EXPERIENCE = [
  {
    type: "work",
    title: "Senior Full-Stack Developer",
    company: "TechNova Inc.",
    period: "2022 – Present",
    description: "Led development of a SaaS platform serving 50k+ users. Built microservices architecture with Node.js and React, improving system performance by 40%.",
    skills: ["React", "Node.js", "MongoDB", "AWS"],
  },
  {
    type: "work",
    title: "Full-Stack Developer",
    company: "StartupXYZ",
    period: "2020 – 2022",
    description: "Developed and maintained 3 production web applications. Collaborated with a team of 8 engineers on agile sprints. Reduced API response time by 60% through optimization.",
    skills: ["Vue.js", "Express", "PostgreSQL", "Docker"],
  },
  {
    type: "work",
    title: "Frontend Developer Intern",
    company: "Creative Agency Co.",
    period: "2019 – 2020",
    description: "Built responsive web interfaces for 15+ client projects. Learned best practices for component architecture and performance optimization.",
    skills: ["React", "JavaScript", "CSS", "Figma"],
  },
  {
    type: "education",
    title: "Bachelor in Economics",
    company: "Kalika Multiple Campus",
    period: "2020 – 2024",
    description: "Graduated with honors. Specialized in Software Engineering and Distributed Systems. Final thesis on real-time collaborative applications.",
    skills: ["Algorithms", "Data Structures", "OS", "Networks"],
  },
];

export const SAMPLE_PROJECTS = [
  {
    _id: "1",
    title: "CollabFlow — Real-time Project Manager",
    description: "A Jira-inspired project management tool with real-time updates, drag-and-drop kanban boards, team chat, and detailed analytics. Supports 1000+ concurrent users.",
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&auto=format",
    technologies: ["React", "Node.js", "MongoDB", "Socket.io", "Redis"],
    githubLink: "https://github.com",
    liveLink: "https://demo.example.com",
    featured: true,
  },
  {
    _id: "2",
    title: "NeuralShop — AI E-Commerce",
    description: "Modern e-commerce platform with AI-powered product recommendations, smart search, and seamless checkout flow. Integrated Stripe payments and real-time inventory.",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&auto=format",
    technologies: ["Next.js", "TypeScript", "PostgreSQL", "Stripe", "AWS"],
    githubLink: "https://github.com",
    liveLink: "https://demo.example.com",
    featured: true,
  },
  {
    _id: "3",
    title: "DevPulse — Developer Analytics",
    description: "GitHub analytics dashboard showing coding patterns, contribution trends, and productivity insights. Visualizes data with interactive D3.js charts.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format",
    technologies: ["React", "Express", "D3.js", "GraphQL", "MongoDB"],
    githubLink: "https://github.com",
    liveLink: "https://demo.example.com",
    featured: false,
  },
  {
    _id: "4",
    title: "CryptoTrack — Portfolio Tracker",
    description: "Real-time cryptocurrency portfolio tracker with price alerts, profit/loss analysis, and portfolio diversification insights. Syncs with 20+ exchanges.",
    image: "https://images.unsplash.com/photo-1640340434855-6084b1f4901c?w=600&auto=format",
    technologies: ["Vue.js", "Python", "FastAPI", "Redis", "PostgreSQL"],
    githubLink: "https://github.com",
    liveLink: "https://demo.example.com",
    featured: false,
  },
];
